@echo off
IF NOT EXIST lastrev.txt (
    echo 0 > lastrev.txt
)

set REVISION=

for %%X in (svn.exe) do (set FOUNDSVN=%%~$PATH:X)

if defined FOUNDSVN (
    FOR /F "tokens=2 skip=4" %%G IN ('svn info --revision HEAD ..\..') DO IF NOT DEFINED REVISION SET REVISION=%%G
) else (
    SET REVISION=99999
)


FOR /F %%H IN (lastrev.txt) DO SET LASTREVISION=%%H

echo Current revision is %REVISION%
echo Last revision is %LASTREVISION%

IF %LASTREVISION% NEQ %REVISION% (
    echo // generated by svnrev.cmd > ..\..\steam_api\buildnumber.h
    echo #define BUILDNUMBER %REVISION% >> ..\..\steam_api\buildnumber.h
    echo #define BUILDNUMBER_STR "%REVISION%" >> ..\..\steam_api\buildnumber.h
    echo #define BUILDHOST "%COMPUTERNAME%" >> ..\..\steam_api\buildnumber.h
    echo %REVISION% > lastrev.txt
)